name: app-tv-build-action-dev

on:
    workflow_dispatch:
    push:
        branches:
            - dev
        paths:
            - 'simple_live_tv_app/**'

jobs:
    # AndroidTV
    build-android-tv:
        runs-on: macos-latest
        permissions:
            contents: write
        env:
            TV_KEYSTORE_BASE64: ${{ secrets.TV_KEYSTORE_BASE64 }}
            TV_STORE_PASSWORD: ${{ secrets.TV_STORE_PASSWORD }}
            TV_KEY_PASSWORD: ${{ secrets.TV_KEY_PASSWORD }}
            TV_KEY_ALIAS: ${{ secrets.TV_KEY_ALIAS }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  ref: dev

            # Android TV 签名
            - name: Decode Android TV keystore
              if: env.TV_KEYSTORE_BASE64 != ''
              uses: timheuer/base64-to-file@v1.2
              id: android_tv_keystore
              with:
                  fileName: keystore_tv.jks
                  encodedString: ${{ env.TV_KEYSTORE_BASE64 }}
            - name: Create Android TV key.properties
              if: env.TV_KEYSTORE_BASE64 != ''
              run: |
                  echo "storeFile=${{ steps.android_tv_keystore.outputs.filePath }}" > simple_live_tv_app/android/key.properties
                  echo "storePassword=${{ env.TV_STORE_PASSWORD }}" >> simple_live_tv_app/android/key.properties
                  echo "keyPassword=${{ env.TV_KEY_PASSWORD }}" >> simple_live_tv_app/android/key.properties
                  echo "keyAlias=${{ env.TV_KEY_ALIAS }}" >> simple_live_tv_app/android/key.properties

            - name: Setup Java environment
              uses: actions/setup-java@v4
              with:
                  distribution: zulu
                  java-version: '17'
                  cache: gradle

            - name: Setup Flutter environment
              uses: subosito/flutter-action@v2
              with:
                  flutter-version: '3.32.0'
                  cache: true

            - name: Get Flutter dependencies
              run: cd simple_live_tv_app && flutter pub get

            - name: Install fast-forge
              run: |
                  git clone https://github.com/fastforgedev/fastforge.git
                  cd fastforge
                  dart pub global activate melos
                  melos run activate

            - name: Build Android TV APK
              run: |
                  cd simple_live_tv_app
                  flutter build apk --release --split-per-abi
                  cd build/app/outputs/flutter-apk
                  for file in app-*-release.apk; do
                    abi=$(echo "$file" | sed -E 's/app-(.*)-release\.apk/\1/')
                    mv "$file" "app-tv-${abi}-release.apk"
                  done

            - name: Upload Android TV APK artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: android_tv
                  path: simple_live_tv_app/build/app/outputs/flutter-apk/app-tv-*-release.apk

            - name: AndroidTV build done
              run: echo "🍏 AndroidTV build done."

    release-dev:
        needs: [build-android-tv]
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/download-artifact@v4
              with:
                  path: artifacts
                  merge-multiple: true

            - name: Generate release timestamp
              id: datetime
              run: echo "value=$(date +'%Y-%m-%d %H:%M')" >> "$GITHUB_OUTPUT"

            - name: Install GitHub CLI
              run: sudo apt-get update && sudo apt-get install -y gh

            - name: Upload TV release assets
              run: |
                  gh release create dev ./artifacts/* \
                    --notes "Automated dev build at ${{ steps.datetime.outputs.value }}" \
                    --prerelease --title "dev ${{ steps.datetime.outputs.value }}" --repo ${{ github.repository }} || true
                  gh release upload dev artifacts/* --clobber --repo ${{ github.repository }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Release updated
              run: echo "🎉 TV APK added to dev pre-release."
